alphagov/di-ipv-cri-uk-passport-front

.gitignore
manifest.yml
package.json
src/assets/javascripts/app.js
src/assets/scss/application.scss
yarn.lock

Add build script to package.json and missing devDependencies
Add new manifest file to be used on PaaS
Add temporary css files for build script to run
Update gitignore
To fix the build job on the concourse pipeline and allow the app to be deployed onto PaaS
- [PYI-455](https://govukverify.atlassian.net/browse/PYI-455)

Add build script and missing dependencies and create manifest file for PaaS application

---

index.js
local.Dockerfile
package.json

BAU: Add docker file to be used during localstartup
BAU: Setup 9229 debugging port for remote debugging the docker container
So that the app can be deployed within docker as a part of the localstartup and then a remote debugger can be attached to the running docker container.

BAU: Setup localstartup docker file and remote debugging

---

src/app.js
src/app/controllers/done.js
src/app/controllers/validate.js
src/app/steps.js
src/locales/en/pages.yml
src/views/passport/done.html

PYI-460: Handle response from cri-passport api and display the sent/received fields on the done page.
To be able to track the data being returned back from DCS and allow for future oauth flows to continue.
- [PYI-460](https://govukverify.atlassian.net/browse/PYI-460)

PYI-460: Handle response from cri-passport-back api 

---

.github/workflows/pre-merge-checks.yml
.nycrc.yml
package.json
sonar-project.properties
yarn.lock

Run SonarCloud checks before PR merge
All our over repos use Sonarcloud

BAU: Add Sonarcloud coverage

---

.yarnrc
local.Dockerfile
package.json

Update yarn version to be 1.22.17
PaaS updated their buildpacks which removed the old yarn version

BAU: Upgrade the yarn version

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js

Update the auth redirect URL to append the auth code.
Because now the core-front already contains a query param for the criId value.
- [PYI-550](https://govukverify.atlassian.net/browse/PYI-550)

PYI-550: Update redirect uri to append the auth code query param

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/app/oauth2/router.js
src/lib/config.js

create new method in middleware to send sharedAttributes to the new lambda
The new lambda decodes, verifies its signature and return the claim as Json
- [PYI-584](https://govukverify.atlassian.net/browse/PYI-584)

PYI-584 add new middleware method to send JWT to lambda

---

src/app/oauth2/middleware.js

Add try catch around the axios post request for the jwt verification lambda call.
Ensures the passport-front will handle any errors being returned back from the lambda.
- [PYI-621](https://govukverify.atlassian.net/browse/PYI-621)

Add error handling around axios request for jwt verification

---

manifest.yml

Add environment var to name of deployed app for passport front.
Make it easier to deploy the app to different environments.

BAU: Setup passport-front app to be deployed to multiple environments

---

manifest.yml

Add missing API_BASE_URL env var needed for passport-front to send requests to passport-back
Adds required variable that will be used on any future deployments to different environments.

BAU: Add API_BASE_URL env var to pasport-front manifest file

---

manifest.yml

Hard code the end of the api url, since the "environment" var setup is different to what is used on the current dev gateway stage name

BAU: Temporary fix for the passport cri api url until new pipelines setup for it

---

src/app/oauth2/middleware.js
src/app/passport/controllers/validate.js
src/lib/config.js

The endpoints on the backend have changed to hopefully be more
intuitive. This updates the frontend to use them
The backend changes are here: The endpoints on the backend have changed to hopefully be more
intuitive. This updates the frontend to use the.
- [PYI-788](https://govukverify.atlassian.net/browse/PYI-788)

PYI-788: Update backend URLs

---

src/app/passport/controllers/validate.js

Middlenames can be empty and DCS does not like empty strings

BAU: Fix DCS error with middlenames

---

src/app/oauth2/router.js
src/app/passport/steps.js

Removed done page, after validation client will be redirected to callback
- [PYIC-845](https://govukverify.atlassian.net/browse/PYIC-845)

PYIC-845 Removed done page, after validation client will be redirected to callback

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js

Handle shared credential errors
Refactored code to call next once in the parseSharedAttributesJWT routine, an invalid page was shown because next was incorrectly called twice.

Handle shared credential errors

---

.github/dependabot.yml

Add a dependabot config file. Copied from kbv front as a first iteration.
We want to have dependabot help us keep our dependencies up to date

BAU: Add a dependabot config file

---

src/app/passport/controllers/validate.js

Add user_id to header for authorization request
- [PYIC-980](https://govukverify.atlassian.net/browse/PYIC-980)

PYIC-980: Add user_id to header for authorization request

---

package.json

Paas has changed there node version & yarn needs to be updated too
We would have more control over Node version when we move to Fargate and use docker
Builds will fail due to unsupported node version on paas and yarn

BAU: Update node version & yarn version

---

.github/workflows/post-merge.yml

Changes to workflow to fix build.
File not being parsed by gh workflow.  Despite showing a problem on screen as being line 13, the issue was further down the file with some incorrect indentation.
- [PYIC-1214](https://govukverify.atlassian.net/browse/PYIC-1214)

[PYIC-1214] Added whitespace to fix build

---

src/views/passport/details.html

PYIC-1043: Add feedback link

---

package.json
yarn.lock

Reverts alphagov/di-ipv-cri-uk-passport-front#95

Revert "BAU: Bump govuk-frontend from 4.0.1 to 4.1.0"

---

.nycrc.yml
package.json
src/assets/javascripts/app.js
yarn.lock

Fixed javascript build step to add and minify govFrontEnd javascript from node modules

BAU - fix javascript build step 

---

.github/workflows/checkov.yml

Checkov is a static analysis tool for infrastructure-as-code. It
will spot common mistakes and flaws in our CFN template. For now
it will run when the core-back template changes but should not
fail the PR build.
Rolling out to all IPV and Passport CFN templates.

PYIC-1073 Run Checkov on PRs

---

src/app/passport/fields.js
src/locales/en/fields.yml

This pull request updates most of the changes identified in testing for passport form validation and related error messages from [the JIRA ticket PYIC-1183](https://govukverify.atlassian.net/browse/PYIC-1183).
The `fields.yml` file was changed to add error states and messages that weren’t yet implemented, and to change error messages that were in place so they matched the content designer’s work.
The `fields.js` file was changes to add extra tests to the current form validation.
- [PYIC-1183](https://govukverify.atlassian.net/browse/PYIC-1183)

[PYIC-1183] Initial validation updates

---

src/locales/en/default.yml

This PR updates the order of links in the footer
the code in default.yml was updated according to the content team’s requirements
To reflect the order in other parts of the PYI journey
- [PYIC-1222](https://govukverify.atlassian.net/browse/PYIC-1222)

[PYIC-1222] Update footer links

---

deploy/template.yaml

added a default value for apibaseurl while we get ready to remove it. 
added a default value for apibaseurl while we get ready to remove it. 
- [PYIC-1307](https://govukverify.atlassian.net/browse/PYIC-1307)

PYIC-1307 added default value for removal

---

.pre-commit-config.yaml

This adds pre-commit configuration file for configuring pre-commit git hooks (this requires the installation of pre-commit)
This adds pre-commit configuration file for configuring pre-commit git hooks (this requires the installation of pre-commit)
This is added so we can make sure cloud formation files are linted and other basics are checked.
- [PYIC-1399](https://govukverify.atlassian.net/browse/PYIC-1399)

PYIC-1399 Added pre-commit config

---

.pre-commit-config.yaml
README.md

This updates the documentation and includes notes on how to use / install the pre-commit hooks.
Documentation was requested for usage.
- [PYIC-1399](https://govukverify.atlassian.net/browse/PYIC-1399)

PYIC-1399 updated Readme

---

README.md

fixed formatting of readme
fixed formatting of readme
- [PYIC-1399](https://govukverify.atlassian.net/browse/PYIC-1399)

PYIC-1399 fixed readme - formatting issues

---

.github/workflows/checkov.yml
deploy/template.yaml

Added checkov fixes
Run checkov on existing Cloudformation and fix errors/notifications
- [PYIC-XXXX](https://govukverify.atlassian.net/browse/PYIC-XXX)

PYIC-1294 Added Checkov fixes

---

deploy/template.yaml

This is being set via the mappings section and has been removed from the
Concourse CI configuration so is safe to remove.
To be merged after https://github.com/alphagov/di-ipv-config/pull/739
- [PYIC-1460](https://govukverify.atlassian.net/browse/PYIC-1460)

PYIC-1460 Remove desired task count param

---

src/app/passport/fields.js
src/app/passport/fields.test.js
src/locales/en/fields.yml
src/views/passport/details.html

added custom validation hmpo to check if first and middle names do not exceed 30 characters
- [PYIC-1936](https://govukverify.atlassian.net/browse/PYIC-1936)

PYIC-1936 - added validation using hmpo to check if first and middle names do not exceed 30 characters

---

deploy/template.yaml

Create new passport front sessions table.
This dynamodb table will be used to store the passport front session details.
- [PYIC-1482](https://govukverify.atlassian.net/browse/PYIC-1482)

PYIC-1482: Create passport front sessions dynamodb table

---

deploy/template.yaml

Added TLS to Access Log Bucket
This is a requirement from the pen test report. 
- [PYIC-1477](https://govukverify.atlassian.net/browse/PYIC-1477)

PYIC-1477 Added TLS to Access Log Bucket

---

deploy/template.yaml

Reduce prod desired count
Without shared session storage we can only run one instance.

BAU: Reduce prod desired count

---

deploy/template.yaml

added deletion protection to LB
Requirement from pen testing results.
- [PYIC-1478](https://govukverify.atlassian.net/browse/PYIC-1478)

PYIC-1478 added deletion protection to LB

---

src/lib/config.js

Add missing front-end config env var value for the DynamoDB table name

Add config env var for session table name

---

src/views/errors/error.html

The page currently seen in the journey is completely blank.
The hmpoPageKey was modified to `pages.errors.error` to link the page template with the required page content.
This produces the designed state of the error page.
- [PYIC-1467](https://govukverify.atlassian.net/browse/PYIC-1467)

PYIC-1467 Render error page correctly

---

.gitignore
src/app.js
src/app/oauth2/middleware.js
src/app/passport/controllers/validate.js

Log passportSessionId
This adds a new field to the request and app logs, `passportSessionId`.
This will log the same session ID as the request logs currently log,
however the name will help to differentiate it from other session IDs we
may log in the future, such as a persistent session ID. The backend is
also set to log this value under this field name so the front and back
logs can be tied together easily. This naming is also consistent with
how we're logging the ipvSessionId in the core.
This also adds some light app logs, mostly as a way to demonstrate how
to use the logger. Passing in the request object is required due to the
use of the `meta` configuration block. If the request is not passed in
the logger will just log `undefined`.
An example app log generated with this config:
``` …
```

PYIC-1490: Log passportSessionId

---

src/app/passport/controllers/validate.js
src/app/passport/controllers/validate.test.js

PYIC-1566 - Remove code to pass auth params and userId into the request
- [PYIC-1566](https://govukverify.atlassian.net/browse/PYIC-1566)

PYIC-1566 - Remove code to pass auth params and userId into the request

---

.github/workflows/codeql.yml
.github/workflows/concourse-post-merge.yml
.github/workflows/secure-post-merge-to-build.yml
deploy-sp/template.yaml

PYIC-1714 Added necessary components for secure pipeline
new file:   .github/workflows/codeql.yml
new file:   .github/workflows/concourse-post-merge.yml
new file:   .github/workflows/secure-post-merge-to-build.yml
new file:   deploy-sp/template.yaml
Added necessary components for secure pipeline
- [PYIC-1714](https://govukverify.atlassian.net/browse/PYIC-1714)

PYIC-1714 Added necessary components for secure pipeline

---

.github/workflows/post-merge.yml

PYIC-1714 artifact bucket rename
PYIC-1714 artifact bucket rename
- [PYIC-1714](https://govukverify.atlassian.net/browse/PYIC-1714)

PYIC-1714 artifact bucket rename

---

src/locales/en/pages.errors.yml

Headings for error pages are clearer for the user.
The yaml file has text removed from the page headings.
A content audit for the welsh translation work revealed an earlier version of the text had been used.
- [PYIC-1736](https://govukverify.atlassian.net/browse/PYIC-1736)

PYIC-1736 update pages after content audit

---

deploy-sp/template.yaml
deploy/template.yaml

Hardcoded IPVCriUkPassportPrivateAPIGatewayID which is imported from
passport-back stack as they are both being renamed.
Changed export from ${AWS::StackName}-PassportFrontGatewayID to PassportFrontApiGatewayID-${Environment}
As the stackname will not always contain the proper environment name -
this keeps things simple when importing the resource by dns.
modified:   deploy-sp/template.yaml
modified:   deploy/template.yaml
Hardcoded IPVCriUkPassportPrivateAPIGatewayID which is imported from
passport-back stack as they are both being renamed.
Changed export from ${AWS::StackName}-PassportFrontGatewayID to PassportFrontApiGatewayID-${Environment}
As the stackname will not always contain the proper environment name -
this keeps things simple when importing the resource by dns.
modified: …

PYIC-1732 PYIC-1733

---

deploy-sp/template.yaml
deploy/template.yaml

Removed hardcoded passport private api gateway and now using imported values. 
Removed hardcoded passport private api gateway and now using imported values. 
- [PYIC-1732](https://govukverify.atlassian.net/browse/PYIC-1732)

PYIC 1732 1733 update stack names

---

src/app.js

- Changed default `i18next` cookie property to `lng` to match [auth team's usage](https://github.com/alphagov/di-authentication-frontend/blob/11bf1617e25e925ab680096f813f9c0d4876792c/src/config/i18next.ts#L8-L11).
- Added allowedLang
- Added fallbackLang
Aligning the cookies means that when the auth team set a preference for a language, that it is applied in the KBV UI as well.
- [OJ-876](https://govukverify.atlassian.net/browse/OJ-876)

feat: Add config for English and Welsh translations

---

.github/workflows/concourse-post-merge.yml
.github/workflows/post-merge.yml
.github/workflows/secure-post-merge.yml

This disables the post-merge pipeline and defaults to the secure
pipeline compatible concourse-post-merge.yml.
Please do not use the deploy/ folder all pipelines now build using the
deploy-sp/ directory.
modified:   .github/workflows/concourse-post-merge.yml
modified:   .github/workflows/post-merge.yml
renamed:    .github/workflows/secure-post-merge-to-build.yml -> .github/workflows/secure-post-merge.yml
This disables the post-merge pipeline and defaults to the secure
pipeline compatible concourse-post-merge.yml.
Please do not use the deploy/ folder all pipelines now build using the
deploy-sp/ directory.
modified:   .github/workflows/concourse-post-merge.yml
modified:   .github/workflows/post-merge.yml
renamed:    .github/workflows/secure-post-merge-to-build.yml -> …

PYIC-1732 Concourse-pipeline-compatibility

---

.github/workflows/concourse-post-merge.yml

PYIC-1732 Concourse removed erroneous ~
PYIC-1732 Concourse removed erroneous ~
- [PYIC-1732](https://govukverify.atlassian.net/browse/PYIC-1732)

PYIC-1732 Concourse removed erroneous ~

---

.nycrc.yml
sonar-project.properties
src/app/passport/controllers/prove-another-way.js
src/app/passport/controllers/prove-another-way.test.js
src/app/passport/controllers/validate.test.js
src/app/passport/fields.js
src/app/passport/fieldsHelper.js
src/app/passport/fieldsHelper.test.js

Narrowed down to the correct files we want to be testing
Moved function into helper to improve testing ability of function instead of the whole file which isnt necessary
Added test to make sure branches are being hit
Fix sonarcloud codesmells checking the assets
Important to keep our coverage high and accurate

BAU: Fix and improve testing coverage

---

package.json
yarn.lock

Reverts alphagov/di-ipv-cri-uk-passport-front#274

Revert "BAU: Bump aws-sdk from 2.1189.0 to 2.1210.0"

---

src/app/passport/fields.js

updated file reference to fix build issue

BAU - updated file reference to fix build issue

---

deploy-sp/template.yaml

PYIC-1919 updated template to use hardcoded passport back private api gateway ids - to remove import dependency
PYIC-1919 updated template to use hardcoded passport back private api gateway ids - to remove import dependency

PYIC-1919 updated template to use hardcoded passport back private api gateway ids - to remove import dependency

---

deploy-sp/template.yaml

PYIC-1919 updated passport-stag gateway id
PYIC-1919 updated passport-stag gateway id
passport-staging gateway ids rebuilt last night - since they are still decoupled the staging gateway id needs to be changed - this  PR does that should make things work again. 

PYIC-1919 updated passport-stag gateway id

---

deploy-sp/template.yaml

PYIC-1919 updates to staging api gateway id
PYIC-1919 updates to staging api gateway id

PYIC-1919 updates to staging api gateway id

---

deploy-sp/template.yaml

PYIC-1919 updates to build api gateway id
PYIC-1919 updates to build api gateway id

PYIC-1919 updates to build api gateway id

---

deploy/template.yaml

PYIC-1919 reconnecting passport-front and back
PYIC-1919 reconnecting passport-front and back

PYIC-1919 reconnecting passport-front and back

---

deploy/template.yaml

Added ecs fargate auto scaling
Added ecs fargate auto scaling
- [PYIC-1891](https://govukverify.atlassian.net/browse/PYIC-1891)

PYIC-1891 ECS Fargate Auto-Scaling

---

deploy/template.yaml

Fix ECSServiceTaskDefinition null import value.
Null due to incorrect indentation.
- [LIME-131](https://govukverify.atlassian.net/browse/LIME-131)

LIME-131 Fix ECSServiceTaskDefinition null import value.

---

deploy/template.yaml

Fixed casing on ok action
to enable recovery after alerts

LIM-209: Fixed casing on ok action

---

src/locales/cy/default.yml
src/locales/cy/pages.errors.yml
src/locales/en/default.yml
src/locales/en/pages.errors.yml

This PR updates all content related to the One Login name change

LIME-404 - Content updates to reflect product name change

---

deploy/template.yaml
src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/app/passport/controllers/validate.js

- This restores LIME-399 changes.
- problem with deploy identified and addressed.

Restore "LIME-399 - 'Page not found' error is incorrectly appearing in the Passport CRI"

---

deploy/template.yaml
src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/app/passport/controllers/validate.js

- This reverts commit 443fd92d08818dc3c3cbf611fd5eb986222d0809.
- FE stack did not build, was rolled back.
- Associated backend changes of original merge / PR still functional. Do not impact this revert.

Revert "Restore "LIME-399 - 'Page not found' error is incorrectly appearing in the Passport CRI""

---

src/locales/cy/default.yml
src/locales/en/default.yml
src/views/passport/details.html

Retry banner welsh translations bug fix

LIME-668 - RetryBanner translation bug fix
