alphagov/di-ipv-cri-uk-passport-front

src/app/fields.js
src/locales/en/fields.yml

Update the passport details validation to match DCS validation.
- Passport number must be between 1and 899999999
- Expiry date must not be more than 18 months in the past
To bring our validation in line with what the DCS service expects.
- [PYI-458](https://govukverify.atlassian.net/browse/PYI-458)

PYI-458: Update passport details validation to match with DCS validation

---

src/app.js

Update cri-passport front's session cookie name to be unique.
When running locally the 2 front-end apps used the same cookie name so they would override each other and session data would be lost.
- [PYI-491](https://govukverify.atlassian.net/browse/PYI-491)

PYI-491: Change session cookie name to be unique for passport-front

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js

When making call to to the jwt-verification api, the client_id sent from the Core Front request is forwarded via the header.
The change enables the jwt-verification api to use the client_id and to load the corresponding certs from KMS.
- [PYI-621](https://govukverify.atlassian.net/browse/PYI-621)

PYI-621: Pass client_id in the header when posting to the jwt-verification api

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/app/oauth2/router.js
src/app/passport/controllers/root.js
src/app/passport/controllers/root.test.js
src/app/passport/steps.js
src/lib/config.js

Co-authored-by Lai Tang <lai.tang@digital.cabinet-office.gov.uk>
Co-authored-by Sunil Dussoye <sunil.dussoye@digital.cabinet-office.gov.uk>
- Set the returned JSON from the jwt-verification lambda within the hmpo-app session
- At the root of the hmpo-form load the shared-attribute session data and move it into the journeyModel
- Add additional unit tests
Data entered into the journeyModel is automatically picked up by the fields, so now the shared attributes values are pre-populated into the passport form.
- [PYI-585](https://govukverify.atlassian.net/browse/PYI-585)

PYI-585: Autofill passport form with shared attributes value if present

---

package.json
src/app.js
yarn.lock

Express by default does not always handle async/await errors, resulting
in an unhandled error and a crashed server.
This fix uses the express-async-errors library to monkepatch the Express
framework to handle the errors.
**This is the same implementation that the kbv team use on their front-end apps.**
I've tested this on passport-front by sending an incorrect post request to the /oauth2/authorize endpoint. Without this fix the app crashes, but with it the app keeps running and returns the something went wrong error page.
- [PYI-725](https://govukverify.atlassian.net/browse/PYI-725)

PYI-725: Fix async express error bug

---

manifest.yml

So that the api gawteway can be dynamically supplied by the deploy
pipelines.
- [PYIC-138](https://govukverify.atlassian.net/browse/PYIC-138)

PYIC-138: Make API_BASE_URL a variable

---

src/app/passport/controllers/root.js

We weren't using the `?.` operator when checking birth dates. This meant
that an error was getting thrown rather than returning undefined.
The values being queried in the shared attributes are actually wrong so
will never find a value, but fixing that is for another PR.

BAU: Use safe chaining in root controller

---

.github/pull_request_template.md
src/app/passport/controllers/validate.js
src/app/passport/controllers/validate.test.js
src/app/passport/fields.js
src/app/passport/steps.js
src/locales/en/fields.yml
src/locales/en/pages.yml
src/views/passport/details.html

The prototype splits given names into first name and middle names.
This concats them into a single array so within the backend its still passing the correct field forenames to the backend
Update the page template to reflect the prototype designs
_This does not meet the designs fully. For now this is acceptable as designs may change after user research._
- _The headings are using incorrect css which we have raised an issue with hmpo-form-wizard, tracked by: (https://govukverify.atlassian.net/browse/KBV-292)_
- _As we are restricted with the hmpo-form-wizard, we cannot add additional labels or headers if they do not belong to a text/check/input/radio box. We cannot also add the custom css that the prototype designs use_
We want to align with the designs from the prototype
- …

PYIC-841: Update passport to match prototype 

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js

Return state in auth response
We need to return the state value given to us in the auth request back
to the user in the auth response. This change pulls it from the frontend
session and sets it as a query param.
This also moves to using a proper URL object to parse the redirect URL
and add the query string params. This is important because if the
redirect URL configured for the client is just a host (ie doesn't
already have any search query params), the client redirect will result
in a 404. This is because we were just appending a string to the end of
the host that began with an `&`, rather than a '?'. This is the treated
as part of the path and the core front will not be able to resolve it.
- [PYIC-905](https://govukverify.atlassian.net/browse/PYIC-905)

PYIC-905: Return state in auth response

---

src/views/passport/details.html

Replaced the orphaned `label` with a `fieldset` and `legend`.
Labels should be linked to an input - this particular label ("Given names") needed to be linked to both the "First name" and "Middle name" form fields. Grouping a number of inputs together in a fieldset makes semantic sense, allowing browsers and assistive technologies to make better sense of the form.
- [PYIC-928](https://govukverify.atlassian.net/browse/PYIC-928)

PYIC-928 - Wrap middle & first names in fieldset

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/app/shared/oauth.js

PYIC-994 - Update passport-front to redirect the user back to core-front if an Oauth error occurs with the JAR request and the redirect_uri is visible.
PYIC-945 - Update passport-back to return the redirect_uri value alongside the details of the error object
PYIC-947 - Update passport-front to display error page if JWT is missing cannot be found
- [PYIC-934](https://govukverify.atlassian.net/browse/PYIC-934)
- [PYIC-994](https://govukverify.atlassian.net/browse/PYIC-994)
- [PYIC-945](https://govukverify.atlassian.net/browse/PYIC-945)
- [PYIC-947](https://govukverify.atlassian.net/browse/PYIC-947)

PYIC-934 Passport front error handling

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/app/oauth2/router.js
src/app/passport/controllers/root.js
src/app/passport/controllers/root.test.js
src/app/passport/controllers/validate.js
src/app/passport/controllers/validate.test.js
src/lib/config.js

Refactored code to call jwt-authorization-request and to store the decrypted JWT in user's session.
The decrypted data stores oAuthData in the authParams property and shared claims (formerly known as shared attributes) in the shared_claims property.
To sync with passport-back's JAR changes
- [PYIC-951](https://govukverify.atlassian.net/browse/PYIC-951)

PYIC-951 Refactored code to call jwt-authorization-request

---

Dockerfile

Create Dockerfile that can build an image of the frontend code.
Add Dockerfile using node:16.13.1-alpine3.15 to build a passport-front image
Require an image for Fargate deployments
- [PYIC-1136](https://govukverify.atlassian.net/browse/PYIC-1136)

[PYIC-1136] - Add Dockerfile

---

deploy/template.yaml

Add ECS deploy template to create ECS cluster, it's dependencies and a Passport Frontend Task
See above
Migration to Fargate requires ECS deployment template
- [PYIC-1163](https://govukverify.atlassian.net/browse/PYIC-1163)

PYIC-1163: add ecs deployment template

---

.github/workflows/post-merge.yml

Modifies the github workflow to login to both development and build, in order to push the image back to the development account, tagging as 'latest'
Allow developers in passport to simply pull from latest to get the 'latest' copy for development purposes
- [PYIC-1216](https://govukverify.atlassian.net/browse/PYIC-1216)

[PYIC-1216] Updated workflow to push built image to develop as latest

---

.github/workflows/post-merge.yml

Referred to the wrong repository name in the CI job.
The build couldn't find passport-front-development repo, as it didn't exist.
- [PYIC-1216](https://govukverify.atlassian.net/browse/PYIC-1216)

[PYIC-1216] Fixed name of the build repo

---

deploy/template.yaml

Required to set up custom domain on the api gateway.
- [PYIC-1239](https://govukverify.atlassian.net/browse/PYIC-1239)

PYIC-1239 Export Api Gateway Id

---

src/locales/en/default.yml

The link was originally trying to hit the default "/" route which we never defined.
A service name is required from hmpo-components as it tries to look for it as part of the internationalisation 
The "Prove your identity" header link which goes to a 404 page
- [PYIC-1042](https://govukverify.atlassian.net/browse/PYIC-1042)

PYIC-1042: Fix header link

---

src/locales/en/pages.errors.yml

This uses the hmpo bootstrap error handling default.
This replaces the something went wrong error which gets displayed to a user if we dont specify a particular error for that case.
This follows the designs from [figma](https://www.figma.com/file/nglBHtbzJYEeST43Iu1jW3/PYI-DBS-Return-Journey-Mockups-(Unhappy-Paths)): 
passport-front:
We want to show the user some type of actual error message and present a button for them to navigate elsewhere
- [PYIC-1135](https://govukverify.atlassian.net/browse/PYIC-XXX1135)

PYIC-1135: Add technical error (unrecoverable) page

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/app/passport/controllers/validate.js
src/app/passport/controllers/validate.test.js

Update the query params in the callback redirect url
We are now returning oauth errors from passport-back in the shape
```
{
"error": "server_error",
"error_description": "What went wrong"
}
```
This updates the query params in the redirect url to match
- [PYIC-1308](https://govukverify.atlassian.net/browse/PYIC-1308)

PYIC-1308 Update callback redirect url params

---

deploy/template.yaml

S3 access events from the Github Actions artifact bucket will be written
to the ipv-passport-<env>-access-logs bucket and we need to permit log
delivery write in the bucket's ACL.
As per the description this is necesasary to use this bucket to capture s3 server access logs
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket.html#cfn-s3-bucket-accesscontrol
https://aws.amazon.com/premiumsupport/knowledge-center/s3-server-access-log-not-delivered/

PYIC-1286 Permit Log Delivery Write on Access Bucket

---

deploy/template.yaml

Update the access logs bucket policy to permit S3 access logs.
It makes more sense to permit `logging.s3.amazonaws.com` in the policy defined within this template than scattered throughout our code base (so I'll remove it from here: https://github.com/alphagov/di-ipv-config/blob/d0798f5400a7621673278327f2aa18e219c30b1f/cris/passport/deploy/github-identity/template.yaml#L276)
- [PYIC-1290](https://govukverify.atlassian.net/browse/PYIC-1290)

PYIC-1290 Permit S3 Access Logs

---

src/app/passport/controllers/root.js
src/locales/en/default.yml
src/locales/en/pages.errors.yml
src/views/errors/error.html
src/views/errors/page-not-found.html
src/views/errors/session-ended.html
src/views/passport/details.html
src/views/shared/ipv-template.html

Nunjucks design system code has been added to pages to generate the required footer links and beta banner. The footer links are managed in `default.yml`. The `passport/details.html` page is now generated by `shared/ipv-template.html`, which allows global control of page elements.
Pages now match the designed state and provide useful links for users.
- [PYIC-1222](https://govukverify.atlassian.net/browse/PYIC-1222)

[PYIC-1222] Add beta banner and footer links

---

deploy/template.yaml

Changed the capitals to lowercase on the ECS Circuit breaker code 
I removed the capitalisation of the word TRUE and made it lowercase.
To prevent any errors caused by using capitals  
- [PYIC-1280](https://govukverify.atlassian.net/browse/PYIC-1280)

PYIC-1280 Changes to circuit breaker

---

deploy/template.yaml

Use IsNotDevelopment condition to prevent the logging subscription filters from being created on the development environment.
We don't need the subscription filters on the development environment.
- [PYIC-1422](https://govukverify.atlassian.net/browse/PYIC-1422)

Remove the log group subscription filters for the dev environment

---

src/views/shared/ipv-template.html

As with core front-end code, the passport CRI code requires:
- the empty header link to be removed - as this affects keyboard tabbing through the page
- the feedback link to open in a new window as designed and communicate this behaviour to the user 
`ipv-template.html` blocks have been changed and html source code modified
To remove source code that produced inaccessible behaviours, as identified in the DAC audit.
- [PYIC-1481](https://govukverify.atlassian.net/browse/PYIC-1481)

PYIC-1481 fix accessibility issues

---

deploy/template.yaml

Update the target groups on the front-end application load balancer to
use the `/healthcheck` endpoint which will return 200 if the server is
running. This reduces the noise from 400 http status codes in the app
logs which was always a temporary work-around.
As above
As above
To reduce the noise of 404 http codes in the app logs and use the purpose made `/healthcheck` endpoint. The endpoint already exists for example: https://review-p.build.account.gov.uk/healthcheck
- [PYIC-1493](https://govukverify.atlassian.net/browse/PYIC-1493)

PYIC-1493 Update the Target Group Healthcheck

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/app/shared/oauth.js
yarn.lock

When present set the `state` param in the redirect url for recoverable errors when calling the JwtAuthorizationRequest and AuthorizationCode endpoints. For the JwtAuthorizationRequest call passport-back will pass the state param back to us in the error response. For the AuthorizationCode call we have the state already so can pass it directly.
RFC6749 (https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2.1) requires the state param to be included in the redirect uri query alongside the error params (if it is provided in the original client authorization request)
- [PYIC-1449](https://govukverify.atlassian.net/browse/PYIC-1449)

PYIC-1449 Include state param in error redirect url

---

deploy/template.yaml

Move the policy that allows DynamoDB read/write access to the new core-front table to the ECSTaskRole role.
The policy had previously been added to the ECSTaskExecutionRole which was incorrect. The policy needed to be added to the ECSTaskRole instead.

BAU: Move dynamoDB policy to the ECSTaskRole

---

deploy/template.yaml
package.json
src/app.js
yarn.lock

Use DynamoDB instance to store the front-end session details.
So that we are no longer using a temp in memory redis cache for the front-end redis storage. And means we don't need to manage a full redis instance
- [PYIC-1457](https://govukverify.atlassian.net/browse/PYIC-1457)

PYIC-1457: Use dynamoDB to store passport-front session

---

deploy/template.yaml

Set the GTM_ID & ANALYTICS_DOMAIN env vars to passport-front depending on wether it is the prod environment or not.
These values will be used by passport-front during the setup of google tag manager
- [PYIC-1503](https://govukverify.atlassian.net/browse/PYIC-1503)

PYIC-1503: Add the GTM_ID and ANALYTICS_DOMAIN env vars to passport-front

---

.nycrc.yml
package.json
src/app.js

Added middleware setup to rewrite the incoming request header value `x-forwarded-proto` to be https
Updated HMPO-App to 2.3.0 to have the ability to inject custom middleware
The existing infrastructure configuration is causing the Load Balancer to forward the incorrect header `value x-fowarded-proto`.  Infrastructure cannot overwrite the value due to where the TLS termination ends and requires the app to explicitly trust that the original request is secure. 
- [PYIC-1376](https://govukverify.atlassian.net/browse/PYIC-1376)

PYIC-1376 - Rewrite request x-forwarded-proto header

---

deploy/template.yaml

Increased the desired count to 2 for staging/integration/production environments
We can now have multiple front-end instances since we have DynamoDB as our front-end session storage.

BAU: Increase desired count to 2 for staging, integration and production environments

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/app/passport/controllers/root.test.js
src/app/passport/controllers/validate.js
src/app/passport/controllers/validate.test.js
src/app/passport/fields.js

Send session ID to passport back
We're implementing structured logging to make it easy to link requests
in our logs. Currently we have no shared session ID available to
passport back. There is a PR open to start logging a session ID that is
passed in from passport-front, where we currently store a users session
details. Note, this is different to core which has a session table in
the backend.
This adds the session ID of the users frontend session as a header to
the authorize lambdas.
- [PYIC-1484](https://govukverify.atlassian.net/browse/PYIC-1484)

PYIC-1484: Send session ID to passport back

---

deploy/template.yaml

Add the response latency to the passport front API access logs. This
will be useful in Splunk.
As above.
Same change as recently made to core-front https://github.com/alphagov/di-ipv-core-front/pull/289/files. 
Response latency will be useful in Splunk to observe our system.
- [PYIC-1519](https://govukverify.atlassian.net/browse/PYIC-1519)

PYIC-1519 Log Response Latency

---

.gitignore
src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/app/passport/controllers/details.js
src/app/passport/controllers/details.test.js
src/app/passport/controllers/root.js
src/app/passport/controllers/validate.js
src/app/passport/controllers/validate.test.js
src/app/passport/steps.js
src/assets/scss/application.scss
src/lib/config.js
src/locales/en/default.yml
src/views/passport/details.html

Handle new endpoints on passport back:
- First call `check-passport` with the passport details. If "retry" response received, return to details page with an error notification. If "finish" response received, continue as before.
- Second call `build-client-oauth-response` the new endpoint to generate the authorization redirect url to store in session - we now use the full redirect url constructed and returned by the backend rather than generating it in front itself given just the authorization code.
To handle the changes on the backend for the new retries journey
- [PYIC-1563](https://govukverify.atlassian.net/browse/PYIC-1563)
- [PYIC-1564](https://govukverify.atlassian.net/browse/PYIC-1564)
- [PYIC-1565](https://govukverify.atlassian.net/browse/PYIC-1565)

PYIC-1563-5 Update handling response to passport check

---

src/locales/en/default.yml
src/views/shared/banner.njk

Updates the cookie banner and footer links to direct to the correct control panel for PYI users.
`default.yml` and `banner.njk` files have been modified to add the correct link, make translations easier, and add a global variable for the link location.
To conform with required specification.
- [PYIC-1591](https://govukverify.atlassian.net/browse/PYIC-1591)

PYIC-1591 update cookie link and banner for Passport CRI

---

deploy/template.yaml

Temporarily remove some log group subscription filters from staging
because they were deleted manually by mistake. This change will make
CFN's state align with reality, then this can be reverted and CFN will
recreate the resources.
As above.
As above.
Some logging is broken from passport front in staging. This will fix the drift as reported below.
```
GDS11321:drift dan.worth$ aws-vault exec passport-staging-admin -- ./detect_drift.sh passport-front-staging | grep DELETED
APIGWAccessLogsGroupSubscriptionFilter  AWS::Logs::SubscriptionFilter              DELETED
ECSAccessLogsGroupSubscriptionFilter    AWS::Logs::SubscriptionFilter              DELETED
```

BAU Fix stack drift

---

deploy/template.yaml

This reverts commit 6c8d319fb22bb42504e614cccaa780c5733a5bb3.
The commit being reverted temporarily removed two log group subscription
filters from staging in order to bring the CFN stack state back into alignment
with reality. Reverting the commit will make CFN recreate them and thus
fix the drift.
As above
As above
The commit being reverted has been deployed https://cd.gds-reliability.engineering/teams/di-ipv/pipelines/cri-passport-deploy-to-production/jobs/deploy-passport-front-ecs/builds/58#L62c5845d:3
There is no more drift caused by deleted resources, thus reverting the commit will now make CFN recreate the missing log group subscription filters and we'll see logs in Splunk again.
```
GDS11321:drift dan.worth$ aws-vault exec passport-staging-admin -- ./detect_drift.sh …
```

Revert "BAU Fix stack drift"

---

src/app/oauth2/middleware.js
src/app/oauth2/middleware.test.js
src/app/passport/controllers/root.js
src/app/passport/controllers/root.test.js

Stop storing authParams in session, store only shared_claims
- [PYIC-1610](https://govukverify.atlassian.net/browse/PYIC-1610)

PYIC-1610 stop storing authParams in session, store only shared_claims

---

utils/README.md
utils/deploy_to_dev_env.sh

Allow passing one of a,b,c as first arg to specify which of the now 3 passport dev envs to deploy to
eg. `aws-vault exec passport-dev -- ./deploy_to_dev_env.sh b`
We now have 3 passport development envs

BAU Update deploy script to allow passing in env arg

---

src/app.js

Update the logging config to use the value stored in `session.passportSessionId` when adding `passportSessionId` to logs.
The passportSessionId was previously the same as the frontend session. With the updates to the passport cri to enable retrying passport entry, we have updated the session model such that passport back has its own session that is shared with passport front.
Passport front was still logging its session.id as the passportSessionId.

BAU: Update frontend logging to use correct passportSessionId

---

src/app/passport/controllers/prove-another-way.js
src/app/passport/controllers/prove-another-way.test.js
src/app/passport/controllers/validate.js
src/app/passport/fields.js
src/app/passport/steps.js
src/assets/javascript/application.js
src/locales/en/default.yml
src/locales/en/fields.yml
src/locales/en/pages.yml
src/views/passport/details.html
src/views/passport/prove-another-way.html

Add a route for the user to take if they have arrived at the UK Passport CRI but don’t have a UK Passport, or don’t have the details to hand
- Added new copy and a link to get to the new prove-another-way route in passport details page.
- Added prove-another-way controller and page that allows a user to select an action
- [PYIC-1645](https://govukverify.atlassian.net/browse/PYIC-1645)
- [PYIC-1646](https://govukverify.atlassian.net/browse/PYIC-1646)
- [PYIC-1647](https://govukverify.atlassian.net/browse/PYIC-1647)
- [PYIC-1648](https://govukverify.atlassian.net/browse/PYIC-1648)
- [PYIC-1659](https://govukverify.atlassian.net/browse/PYIC-1659)

PYIC 1645 prove identity another way

---

src/locales/en/default.yml

This update adds a class to the link users click to use the passport escape.
The link has had a class attribute added.
The GA team uses classes to track user interactions.
- [PYIC-1696](https://govukverify.atlassian.net/browse/PYIC-1696) - there is another class to add before this ticket is closed.

PYIC-1696 add class to link for GA consumption

---

package.json
src/views/errors/error.html
src/views/errors/page-not-found.html
src/views/errors/session-ended.html
src/views/passport/details.html
src/views/passport/prove-another-way.html

This change adds a class of `govuk-heading-l` for all `<h1>` tags within the passport CRI.
`package.json` has been updated to require version 5.4.0 of the `hmpo-components` dependency. **This update is required for the change to be visible** on `prove-another-way.html` as this page uses the new `hmpoH1Class` variable in `hmpo-template.njk` in the `hmpo-components` dependency.
Other pages have had their classes changed in the `html` files that generate their source code.
To provide the right configuration for Google Analytics tracking to consume.
- [PYIC-1696](https://govukverify.atlassian.net/browse/PYIC-1696) - second item in the checklist.

PYIC-1696 Add required class to H1s for GA consumption

---

src/locales/en/default.yml
src/locales/en/fields.yml
src/views/shared/banner.njk
src/views/shared/ipv-template.html

This PR ensures that all translatable content in the user interface is managed in the files in `locales/en` for translation into other languages
English text present in nunjucks or html files have been shifted into the relevant yaml file.
So the yaml file holds all the content for the UI, making it easier to manage translations.
- [PYIC-1769](https://govukverify.atlassian.net/browse/PYIC-1769)

PYIC-1769 refactor code so all content is managed in yaml files

---

src/locales/cy/default.yml
src/locales/cy/fields.yml
src/locales/cy/pages.errors.yml
src/locales/cy/pages.yml

This PR adds Welsh language support for the passport form CRI.
4 yaml files are added to `locales/cy` which contain the equivalent content for the information in the `locales/en` folder, including the form fields, error messages, and user interface.
Welsh translation is required for the service to pass service evaluation.
- [PYIC-1876](https://govukverify.atlassian.net/browse/PYIC-1876)

PYIC-1876 Add Welsh language translation yaml files

---

deploy/template.yaml

What changed
Use hardcoded passport back private api dns.
Why did it change
Decoupling the dns to allow overwriting the values in passport back build pipeline.
- [LIME-131](https://govukverify.atlassian.net/browse/LIME-131)

LIME-131 Use hardcoded passport back private api dns.

---

deploy/template.yaml

Restore passport back private api to use dns.
Restoring use of DNS after, decoupling allow overwriting the values in passport back build pipeline.
[LIME-131](https://govukverify.atlassian.net/browse/LIME-131)

LIME-131 Restore passport back private api to use dns.

---

deploy/template.yaml

Restore passport back private api to an imported value.
Restoring use of imported GatewayIds.
[LIME-131](https://govukverify.atlassian.net/browse/LIME-131)

LIME-131 Switch APIGatewayID back to imported value

---

deploy/template.yaml

Removed old prod log subscription
Because the old endpoint is being decommissioned

Removing-CSLS-Rust: Removed the old rust log endpoints

---

src/locales/cy/default.yml
src/locales/cy/fields.yml
src/locales/cy/pages.errors.yml
src/locales/cy/pages.yml

This PR corrects issues discovered during the audit of the Welsh translation by the DWP Welsh translation team.
First commit: One error message was changed and tick marks were replaced by typographically correct apostrophes.
Second commit: There are **unconfirmed** translations of the contentLicence and the copyright footer text added now that the `govuk-frontend` dependency has been bumped to a version that supports changing these.
Changes allow for a better reading experience for Welsh language users.
- [PYIC-1876](https://govukverify.atlassian.net/browse/PYIC-1876)

PYIC-1876: update passport CRI with corrected Welsh content

---

deploy/template.yaml

Added alerts for low and absent task counts and 500 errors
So that we know if the frontend is experiencing any issues

LIME-209: Adding alerts to passport frontend

---

deploy/template.yaml

There was an error in the repo this configuration was copied in from. This sets the CPU scaling value to be 70%

Bau set sensible scaling target

---

src/assets/javascript/application.js

Send the user’s language choice to Google Analytics
Replicating the PR https://github.com/alphagov/di-ipv-cri-common-express/pull/168 in common-express
Which replicates the implementation found in core-front.
https://github.com/alphagov/di-ipv-core-front/commit/7feea5893e98b9b3083d5e8d14189100b1cd4d5a
https://github.com/alphagov/di-authentication-frontend/commit/74ebe4d7c64ea5643d387ee947dc0c6dc44eac5c
https://github.com/alphagov/di-ipv-core-front/pull/572
To track users language choice.
- [LIME-250](https://govukverify.atlassian.net/browse/LIME-250)
[LIME-250]: https://govukverify.atlassian.net/browse/LIME-250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-250 Add language choice analytics

---

.github/workflows/secure-post-merge.yml

Allowing builds to be triggered manually
To unblock the test step in the pipeline

LIME-648: Allow passport front github actions to be manually triggered
